# Generated by Django 2.0.5 on 2019-04-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='0', max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('educationtype', models.CharField(max_length=20)),
                ('loan_datetime', models.DateTimeField()),
                ('loan_amnt', models.CharField(max_length=20)),
                ('int_rate', models.CharField(max_length=20)),
                ('installment', models.CharField(max_length=20)),
                ('fico_range_low', models.CharField(max_length=20)),
                ('total_pymnt', models.CharField(max_length=20)),
                ('total_rec_prncp', models.CharField(max_length=20)),
                ('last_pymnt_amnt', models.CharField(max_length=20)),
                ('last_fico_range_high', models.CharField(max_length=20)),
                ('last_fico_range_low', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
