# Generated by Django 3.0.4 on 2020-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0002_auto_20190411_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='loan_datetime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
